#!/usr/bin/env bash
# Install the colophon: a build-provenance note baked into the deployed image so a tester can
# ask "what version of xyz were you running?" and read it straight off the appliance:
#     commec-colophon              # or: cat /etc/commec-colophon/colophon.json
#
# Sources:
#   /tmp/colophon/*         host-side provenance from build.sh's write_colophon: colophon.json,
#                           pins.json, and -- when the source tree was dirty at build time --
#                           git-status.txt + uncommitted.diff (so the exact state is
#                           reconstructable even if HEAD was not the whole story).
#   /opt/commec/commec.lock the conda lockfile GENERATED by THIS build (20-commec.sh), which
#                           pins every package + hash. Copied from the live guest env, not the
#                           host: the host's copy is stale until the post-build download.
set -euxo pipefail

DEST=/etc/commec-colophon
install -d "$DEST"
cp -a /tmp/colophon/. "$DEST"/

# Authoritative package manifest, straight from the env this build just created.
[ -f /opt/commec/commec.lock ] && cp /opt/commec/commec.lock "$DEST/commec.lock"

# World-readable so any user (incl. the kiosk user) can cite the build.
find "$DEST" -type d -exec chmod 0755 {} +
find "$DEST" -type f -exec chmod 0644 {} +

# Convenience reader.
cat > /usr/local/bin/commec-colophon <<'EOF'
#!/bin/sh
# Print this appliance's colophon (build provenance: commit, pins, package versions).
exec cat /etc/commec-colophon/colophon.json
EOF
chmod 0755 /usr/local/bin/commec-colophon
